name: kamiyomu
services:
  kamiyomu:
    image: marcoscostadev/kamiyomu:1.1.1
    container_name: kamiyomu
    restart: unless-stopped
    user: 0:0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      timeout: 10s
      interval: 30s
    ports:
      - target: 8080
        published: "8086"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/manga
        target: /manga
      - type: bind
        source: /DATA/AppData/$AppID/db
        target: /db
      - type: bind
        source: /DATA/AppData/$AppID/logs
        target: /logs
      - type: bind
        source: /DATA/AppData/$AppID/agents
        target: /agents
    x-casaos:
      ports:
        - container: "8080"
          description:
            en_US: WebUI Port
      volumes:
        - container: /manga
          description:
            en_US: Manga media directory
        - container: /db
          description:
            en_US: Database storage
        - container: /logs
          description:
            en_US: Application logs
        - container: /agents
          description:
            en_US: Scanner agents

x-casaos:
  architectures:
    - amd64
    - arm64
  main: kamiyomu
  author: Izanagi11
  category: Media
  title:
    en_US: KamiYomu
  tagline:
    en_US: Web-based manga reader
  description:
    en_US: KamiYomu is a lightweight, self-hosted manga reading server designed to organize and serve your personal manga archives to your browser.
  icon: https://raw.githubusercontent.com/Izanagi11/IzaServerAppstore/refs/heads/main/Apps/Kamiyomu/229410720.png
  port_map: "8086"
  index: /