name: kamiyomu
services:
  kamiyomu:
    cpu_shares: 90
    command: []
    deploy:
      resources:
        limits:
          memory: 33582923776
        reservations:
          devices: []
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080/healthz
      timeout: 10s
      interval: 30s
    image: marcoscostadev/kamiyomu:1.1.1
    labels:
      icon: https://avatars.githubusercontent.com/u/242082676?s=200&v=4
    ports:
      - target: 8080
        published: "8086"
        protocol: tcp
    restart: unless-stopped
    user: 0:0
    volumes:
      - type: bind
        source: /media/Media/Iza's Manga
        target: /manga
      - type: bind
        source: /media/ZimaOS-HD/AppData/KamiYomu/db
        target: /db
      - type: bind
        source: /media/ZimaOS-HD/AppData/KamiYomu/logs
        target: /logs
      - type: bind
        source: /media/ZimaOS-HD/AppData/KamiYomu/agents
        target: /agents
    devices: []
    cap_add: []
    environment: []
    network_mode: bridge
    privileged: false
    container_name: ""
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://avatars.githubusercontent.com/u/242082676?s=200&v=4
  index: /
  is_uncontrolled: false
  port_map: "8086"
  scheme: http
  store_app_id: kamiyomu
  title:
    custom: ""
    en_us: kamiyomu
