name: stash
services:
  stash:
    image: stashapp/stash:latest
    container_name: stash
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: 2m
    environment:
      - STASH_CACHE=/cache/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_PORT=9999
      - STASH_STASH=/data/
    ports:
      - target: 9999
        published: "9999"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /root/.stash
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /data
      - type: bind
        source: /DATA/AppData/$AppID/metadata
        target: /metadata
      - type: bind
        source: /DATA/AppData/$AppID/cache
        target: /cache
      - type: bind
        source: /DATA/AppData/$AppID/blobs
        target: /blobs
      - type: bind
        source: /DATA/AppData/$AppID/generated
        target: /generated
    x-casaos:
      ports:
        - container: "9999"
          description:
            en_US: WebUI Port
      volumes:
        - container: /root/.stash
          description:
            en_US: Configuration files
        - container: /data
          description:
            en_US: Primary media directory
        - container: /metadata
          description:
            en_US: Metadata storage
        - container: /cache
          description:
            en_US: Cache storage
        - container: /blobs
          description:
            en_US: Blob storage
        - container: /generated
          description:
            en_US: Generated files

x-casaos:
  architectures:
    - amd64
    - arm64
  main: stash
  author: Izanagi11
  category: Media
  title:
    en_US: Stash
  tagline:
    en_US: Local media organizer
  description:
    en_US: A self-hosted web application for organizing and serving local media files. 
  icon: https://raw.githubusercontent.com/Izanagi11/IzaServerAppstore/refs/heads/main/Apps/Stash/logo.png
  port_map: "9999"
  index: /