name: profilarr
services:
  parser:
    image: ghcr.io/dictionarry-hub/profilarr-parser:latest
    container_name: profilarr-parser
    restart: unless-stopped
    expose:
      - "5000"

  profilarr:
    image: ghcr.io/dictionarry-hub/profilarr:latest
    container_name: profilarr
    restart: unless-stopped
    depends_on:
      parser:
        condition: service_started
    environment:
      - PARSER_HOST=parser
      - PARSER_PORT=5000
      - PGID=1000
      - PUID=1000
      - TZ=America/Denver
    ports:
      - target: 6868
        published: "6868"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    x-casaos:
      envs:
        - container: TZ
          description:
            en_US: Timezone configuration
      ports:
        - container: "6868"
          description:
            en_US: WebUI Port
      volumes:
        - container: /config
          description:
            en_US: Profilarr configuration data

x-casaos:
  architectures:
    - amd64
    - arm64
  main: profilarr
  author: Izanagi11
  category: Automation
  title:
    en_US: Profilarr
  tagline:
    en_US: Radarr and Sonarr Profile Sync
  description:
    en_US: Profilarr is a companion app for the *Arr suite. It provides a centralized way to easily manage and synchronize custom profiles, release profiles, and quality settings across your Radarr and Sonarr instances.
  icon: https://raw.githubusercontent.com/Izanagi11/IzaServerAppstore/refs/heads/main/Apps/Profilarr/repeat-icons.png
  port_map: "6868"
  index: /