name: anibridge
services:
  anibridge:
    image: ghcr.io/anibridge/anibridge:latest
    container_name: anibridge
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Denver
      - UMASK=22
    ports:
      - target: 4848
        published: "4848"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    x-casaos:
      envs:
        - container: TZ
          description:
            en_US: Timezone configuration
      ports:
        - container: "4848"
          description:
            en_US: WebUI Port
      volumes:
        - container: /config
          description:
            en_US: AniBridge configuration and mapping data

x-casaos:
  architectures:
    - amd64
    - arm64
  main: anibridge
  author: Izanagi11
  category: Automation
  title:
    en_US: AniBridge
  tagline:
    en_US: Anime metadata and tracking bridge
  description:
    en_US: A background bridge application designed to synchronize metadata and tracking statuses across your anime media ecosystem. 
  icon: https://raw.githubusercontent.com/Izanagi11/IzaServerAppstore/refs/heads/main/Apps/Anibridge/229410720.png
  port_map: "4848"
  index: /