name: palworld-server
services:
  palworld:
    image: thijsvanloef/palworld-server-docker:latest
    container_name: palworld-server
    restart: unless-stopped
    stop_grace_period: 30s
    environment:
      - ADMIN_PASSWORD=changeme
      - AUTO_UPDATE_ENABLED=true
      - BACKUP_CRON_EXPRESSION=0 * * * *
      - BACKUP_ENABLED=true
      - COMMUNITY=true
      - CROSSPLAY_PLATFORMS=(Steam,Xbox,PS5,Mac)
      - DELETE_OLD_BACKUPS=true
      - ENABLE_PERF_THREADING_ARGS=true
      - OLD_BACKUP_DAYS=14
      - PGID=1000
      - PLAYERS=20
      - PORT=8211
      - PUID=1000
      - REST_API_ENABLED=true
      - REST_API_PORT=8212
      - RCON_ENABLED=true
      - RCON_PORT=27575
      - SERVER_DESCRIPTION=Palworld Server hosted by Iza
      - SERVER_NAME=Zen's Palworld Server
      - SERVER_PASSWORD=Zen Division
      - TZ=America/Denver
      - UPDATE_ON_BOOT=true
    ports:
      - target: 8211
        published: "8211"
        protocol: udp
      - target: 27015
        published: "27015"
        protocol: udp
      - target: 8212
        published: "8212"
        protocol: tcp
      - target: 27575
        published: "27575"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/palworld-server/palworld
        target: /palworld/
      - type: bind
        source: /media/Hitachi5600/PalworldBackups
        target: /palworld/backups/

x-casaos:
  architectures:
    - amd64
  main: palworld
  author: thijsvanloef
  category: Gaming
  title:
    en_US: Palworld Server
  tagline:
    en_US: Feature-rich dedicated server wrapper
  description:
    en_US: "The community-favorite Palworld dedicated server wrapper. Automatically updates the game on boot and allows you to configure the server directly from the ZimaOS Settings menu."
  icon: https://raw.githubusercontent.com/Izanagi11/IzaServerAppstore/refs/heads/main/Apps/PalworldServer/logo.jpg