name: terraria-docker
services:
  terraria-docker:
    image: passivelemon/terraria-docker:tmodloader-latest
    container_name: terraria-docker
    restart: unless-stopped
    environment:
      - AUTOCREATE=
      - DIFFICULTY=
      - MAXPLAYERS=8
      - MODPACK=WillModPack
      - MOTD=Zen's Terraria Server
      - PASSWORD=ChangeMeBeforeInstalling
      - PGID=1000
      - PUID=1000
      - SEED=
      - SERVERCONFIG=0
      - WORLDNAME=Docker
    ports:
      - target: 7777
        published: "7777"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /opt/terraria/config
    x-casaos:
      envs:
        - container: PASSWORD
          description:
            en_US: Server Password (DO NOT LEAVE AS ChangeMeBeforeInstalling)
        - container: MOTD
          description:
            en_US: Message of the Day
        - container: MODPACK
          description:
            en_US: Name of your TModLoader Modpack
        - container: MAXPLAYERS
          description:
            en_US: Maximum number of players
      ports:
        - container: "7777"
          description:
            en_US: Terraria Game Port
      volumes:
        - container: /opt/terraria/config
          description:
            en_US: World saves, modpacks, and server config data

x-casaos:
  architectures:
    - amd64
    - arm64
  main: terraria-docker
  author: Izanagi11
  category: Gaming
  title:
    en_US: Terraria (TModLoader)
  tagline:
    en_US: Modded Terraria Server
  description:
    en_US: A containerized Terraria server running TModLoader. Use the settings menu before installing to configure your modpack, world name, and set a secure server password.
  icon: https://raw.githubusercontent.com/Izanagi11/IzaServerAppstore/refs/heads/main/Apps/Terraria%20Server/terraria.png