services:
  omni-login:
    image: lscr.io/linuxserver/chromium:latest
    container_name: omni-login
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - CHROME_CLI=https://fansly.com/login
    ports:
      - "3333:3001" 
    volumes:
      - /media/ZimaOS-HD/AppData/omnicapture/server/data/shared_profile:/config
    shm_size: "1gb"
    security_opt:
      - seccomp=unconfined
    restart: unless-stopped

x-casaos:
  architectures:
    - amd64
    - arm64
  # FIXED: Added the hyphen to match the service name exactly
  main_app: omni-login 
  title:
    custom: OmniLogin
  description:
    en_us: Chromium Login For OmniCapture
  category: Utilities
  port_map: "3333"
  author: Iza
  icon: https://github.com/Izanagi11/IzaServerApps/blob/main/Apps/OmniLogin/Google_Chrome_icon-icons.com_66794.png
