name: OmniLogin
services:
  omni-login:
    image: lscr.io/linuxserver/chromium:latest
    container_name: omni-login
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - CHROME_CLI=chrome://new-tab-page
    ports:
      - "3333:3001" 
    volumes:
      # Your existing cookie profile mapping
      - /media/ZimaOS-HD/AppData/omnicapture/server/data/shared_profile:/config
      # ADD THIS NEW LINE: Map your storage drive to the container's download folder
      - /media/WD7200_2/stash/_Unsorted_Junk:/downloads
    shm_size: "1gb"
    security_opt:
      - seccomp=unconfined
    restart: unless-stopped

x-casaos:
  architectures:
    - amd64
    - arm64
  main_app: omni-login 
  title:
    custom: OmniLogin
  description:
    en_us: Chromium Login For OmniCapture
  category: Utilities
  port_map: "3333"
  scheme: "https"
  author: Iza
  icon: https://raw.githubusercontent.com/Izanagi11/IzaServerAppstore/refs/heads/main/Apps/OmniLogin/Google_Chrome_icon-icons.com_66794.png
