name: wizarr
services:
  wizarr:
    image: ghcr.io/wizarrrr/wizarr:latest
    container_name: wizarr
    restart: unless-stopped
    environment:
      - DISABLE_BUILTIN_AUTH=false
      - PGID=1000
      - PUID=1000
      - TZ=America/Denver
    ports:
      - target: 5690
        published: "5690"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID
        target: /data
    x-casaos:
      envs:
        - container: TZ
          description:
            en_US: Timezone configuration
      ports:
        - container: "5690"
          description:
            en_US: WebUI Port
      volumes:
        - container: /data
          description:
            en_US: Wizarr application data

x-casaos:
  architectures:
    - amd64
    - arm64
    - arm
  main: wizarr
  author: Izanagi11
  category: Media
  title:
    en_US: Wizarr
  tagline:
    en_US: Advanced user invitation system for media servers
  description:
    en_US: Wizarr is a tool that allows you to create unique, expiring links to share with your friends and family, allowing them to easily join your Plex, Jellyfin, or Emby server automatically.
  icon: https://raw.githubusercontent.com/Izanagi11/IzaServerAppstore/refs/heads/main/Apps/Wizarr/logo.png
  port_map: "5690"
  index: /