name: neutarr
services:
  neutarr:
    cpu_shares: 90
    command: []
    container_name: neutarr
    deploy:
      resources:
        limits:
          memory: 33582940160
        reservations:
          devices: []
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Denver
    image: iampuid0/neutarr:latest
    labels:
      icon: https://raw.githubusercontent.com/Izanagi11/IzaServerAppstore/refs/heads/main/Apps/Neutarr/neutarr.png
    ports:
      - target: 9705
        published: "9705"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/neutarr
        target: /config
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://raw.githubusercontent.com/Izanagi11/IzaServerAppstore/refs/heads/main/Apps/Neutarr/neutarr.png
  index: /
  is_uncontrolled: false
  port_map: "9705"
  scheme: http
  store_app_id: neutarr
  title:
    custom: neutarr
    en_us: neutarr
