name: neutarr
services:
  neutarr:
    image: iampuid0/neutarr:latest
    container_name: neutarr
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Denver
    ports:
      - target: 9705
        published: "9705"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    x-casaos:
      envs:
        - container: TZ
          description:
            en_US: Timezone configuration
      ports:
        - container: "9705"
          description:
            en_US: WebUI Port
      volumes:
        - container: /config
          description:
            en_US: Neutarr configuration data

x-casaos:
  architectures:
    - amd64
    - arm64
  main: neutarr
  author: Izanagi11
  category: Automation
  title:
    en_US: Neutarr
  tagline:
    en_US: Automated missing media hunter for *Arr
  description:
    en_US: Neutarr is an automated missing media hunter and quality upgrader for your *Arr stack (Sonarr, Radarr, Lidarr, etc.). It routinely scans your libraries and triggers searches for unmet cutoffs or missing episodes to ensure you always have the best quality releases.
  icon: https://raw.githubusercontent.com/Izanagi11/IzaServerAppstore/refs/heads/main/Apps/Neutarr/neutarr.png
  port_map: "9705"
  index: /