name: neutarr
services:
  neutarr:
    cpu_shares: 90
    command: []
    container_name: neutarr
    deploy:
      resources:
        limits:
          memory: 33582940160
        reservations:
          devices: []
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Denver
    image: iampuid0/neutarr:latest
    labels:
      icon: https://imgs.search.brave.com/JNLm-j0M8nk1eIOclc6DYCFak1Qe2bS63LmS39sAax4/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9zdGF0/aWMudmVjdGVlenku/Y29tL3N5c3RlbS9y/ZXNvdXJjZXMvdGh1/bWJuYWlscy8wMDQv/NzQ1LzQzNy9zbWFs/bC9pY29uLXN0cnVj/dHVyZS1vZi10aGUt/bnVjbGV1cy1vZi10/aGUtYXRvbS1pbi1j/aXJjbGUtaWNvbi1h/dG9tLXByb3RvbnMt/bmV1dHJvbnMtYW5k/LWVsZWN0cm9ucy1z/eW1ib2wtb2YtbnVj/bGVhci1lbmVyZ3kt/c2NpZW50aWZpYy1y/ZXNlYXJjaC1hbmQt/bW9sZWN1bGFyLWNo/ZW1pc3RyeS1kZXNp/Z24taWxsdXN0cmF0/aW9uLWZyZWUtdmVj/dG9yLmpwZw
    ports:
      - target: 9705
        published: "9705"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/neutarr
        target: /config
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://imgs.search.brave.com/JNLm-j0M8nk1eIOclc6DYCFak1Qe2bS63LmS39sAax4/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9zdGF0/aWMudmVjdGVlenku/Y29tL3N5c3RlbS9y/ZXNvdXJjZXMvdGh1/bWJuYWlscy8wMDQv/NzQ1LzQzNy9zbWFs/bC9pY29uLXN0cnVj/dHVyZS1vZi10aGUt/bnVjbGV1cy1vZi10/aGUtYXRvbS1pbi1j/aXJjbGUtaWNvbi1h/dG9tLXByb3RvbnMt/bmV1dHJvbnMtYW5k/LWVsZWN0cm9ucy1z/eW1ib2wtb2YtbnVj/bGVhci1lbmVyZ3kt/c2NpZW50aWZpYy1y/ZXNlYXJjaC1hbmQt/bW9sZWN1bGFyLWNo/ZW1pc3RyeS1kZXNp/Z24taWxsdXN0cmF0/aW9uLWZyZWUtdmVj/dG9yLmpwZw
  index: /
  is_uncontrolled: false
  port_map: "9705"
  scheme: http
  store_app_id: neutarr
  title:
    custom: neutarr
    en_us: neutarr
